# Generated by Django 5.1.5 on 2025-01-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('phrase', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('twitter', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('img_1', models.ImageField(upload_to='images/home/')),
                ('img_2', models.ImageField(upload_to='images/home/')),
            ],
        ),
    ]
